// apps/platform-svelte/src/routes/announcements/+page.svelte
<script lang="ts">
	import InView from '$lib/components/animation/in-view.svelte';
	import StaggerContainer from '$lib/components/animation/stagger-container.svelte';
	import EmptyArea from '$lib/components/common/empty-area.svelte';
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { Card, CardContent, CardHeader, CardTitle } from '$lib/components/ui/card';
	import { Megaphone, Plus } from 'lucide-svelte';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	const announcements = $derived(data.announcements);
	const canCreate = $derived(
		!!data.user && (data.user.role === 'admin' || data.user.other_roles.includes('faculty'))
	);

	function timeAgo(date: string | Date): string {
		const d = typeof date === 'string' ? new Date(date) : date;
		const diff = Date.now() - d.getTime();
		const days = Math.floor(diff / (1000 * 60 * 60 * 24));
		if (days === 0) return 'Today';
		if (days === 1) return 'Yesterday';
		if (days < 7) return `${days}d ago`;
		return d.toLocaleDateString();
	}
</script>

<svelte:head>
	<title>Announcements | College Platform</title>
</svelte:head>

<main class="mx-auto w-full max-w-3xl space-y-8 px-4 py-10 md:px-6">
	<InView variant="fly-up">
		<div class="flex items-start justify-between gap-4">
			<div class="space-y-2">
				<div
					class="inline-flex items-center gap-2 rounded-full border border-border/50 bg-muted/40 px-3 py-1 text-xs font-medium text-muted-foreground"
				>
					<Megaphone class="size-3.5 text-primary" />
					Official Updates
				</div>
				<h1 class="text-3xl font-bold tracking-tight md:text-4xl">Announcements</h1>
				<p class="text-muted-foreground">Official news and campus updates.</p>
			</div>
			{#if canCreate}
				<Button href="/announcements/create" class="gap-2">
					<Plus class="size-4" />
					<span class="hidden sm:inline">New</span>
				</Button>
			{/if}
		</div>
	</InView>

	{#if announcements.length === 0}
		<EmptyArea title="No announcements" description="Check back later for updates." />
	{:else}
		<StaggerContainer class="space-y-4">
			{#each announcements as announcement (announcement._id)}
				<Card class="transition-all hover:-translate-y-0.5 hover:shadow-md">
					<CardHeader class="pb-3">
						<div class="flex items-start justify-between gap-3">
							<CardTitle class="text-lg">{announcement.title}</CardTitle>
							<Badge variant="outline" class="shrink-0 text-xs">
								{timeAgo(announcement.createdAt)}
							</Badge>
						</div>
					</CardHeader>
					<CardContent>
						<p class="whitespace-pre-wrap text-sm text-muted-foreground">
							{announcement.content ?? ''}
						</p>
						<div class="mt-3 flex items-center gap-2 text-xs text-muted-foreground">
							<span class="font-medium">By {announcement.createdBy?.name ?? 'Admin'}</span>
							{#if announcement.relatedFor}
								<span>•</span>
								<Badge variant="secondary" class="text-[10px]">{announcement.relatedFor}</Badge>
							{/if}
						</div>
					</CardContent>
				</Card>
			{/each}
		</StaggerContainer>
	{/if}
</main>

// apps/platform/app/(common)/(community)/announcements/page.tsx
import EmptyArea from "@/components/common/empty-area";
import { Badge } from "@/components/ui/badge";
import { AuthButtonLink } from "@/components/utils/link";
import { cn } from "@/lib/utils";
import {
  Bell,
  Calendar,
  GraduationCap,
  Info,
  Megaphone,
  Plus,
  Trophy
} from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { getAnnouncements } from "~/actions/common.announcement";
import { Session } from "~/auth";
import { getSession } from "~/auth/server";
import { RELATED_FOR_TYPES } from "~/constants/common.announcement";
import { changeCase } from "~/utils/string";
import AnnouncementsList from "./list";

export const metadata: Metadata = {
  title: "Announcements",
  description: "Campus news, updates, and official notifications.",
};

// --- Config: Category Icons & Colors ---
const CATEGORY_CONFIG: Record<string, { icon: any; color: string }> = {
  all: { icon: Bell, color: "text-foreground" },
  academic: { icon: GraduationCap, color: "text-blue-500" },
  event: { icon: Calendar, color: "text-orange-500" },
  cultural: { icon: Megaphone, color: "text-purple-500" },
  sports: { icon: Trophy, color: "text-emerald-500" },
  other: { icon: Info, color: "text-muted-foreground" },
};

export default async function AnnouncementsPage(props: {
  searchParams: Promise<{ category?: string }>;
}) {
  const session = await getSession() as Session;
  const searchParams = await props.searchParams;
  const currentCategory = searchParams.category || "all";
  const allAnnouncements = await getAnnouncements();

  // Filter Data
  const filteredAnnouncements =
    currentCategory === "all"
      ? allAnnouncements
      : allAnnouncements.filter((a) => a.relatedFor === currentCategory);

  const tabs = ["all", ...RELATED_FOR_TYPES];

  return (
    <div className="min-h-screen pb-20">
      
      <div className="sticky top-0 z-30 w-full border-b border-border/40 bg-card/50 backdrop-blur-xl rounded-b-lg">
        <div className="mx-auto px-4">
          
          {/* Top Bar */}
          <div className="flex h-16 items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <Megaphone className="size-5" />
              </div>
              <div>
                <h1 className="text-sm font-bold leading-none">Newsroom</h1>
                <p className="text-xs text-muted-foreground mt-1">
                  Latest campus updates
                </p>
              </div>
            </div>

            <AuthButtonLink
              authorized={!!session?.user}
              variant="default"
              size="sm"
              href="/announcements/create"
              className="rounded-full shadow-md shadow-primary/20 gap-2"
            >
              <Plus className="size-4" />
              <span className="hidden sm:inline">New Post</span>
            </AuthButtonLink>
          </div>

          {/* Filter Bar (Scrollable) */}
          <div className="pb-3 -mx-4 px-4 overflow-x-auto no-scrollbar">
            <div className="flex items-center gap-2">
              {tabs.map((cat) => {
                const isActive = currentCategory === cat;
                const config = CATEGORY_CONFIG[cat] || CATEGORY_CONFIG["other"];
                const Icon = config.icon;

                return (
                  <Link
                    key={cat}
                    href={cat === "all" ? "/announcements" : `/announcements?category=${cat}`}
                    className={cn(
                      "flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium transition-all hover:bg-muted whitespace-nowrap",
                      isActive
                        ? "bg-primary/10 border-primary/20 text-primary ring-1 ring-primary/20"
                        : "bg-background border-border/50 text-muted-foreground"
                    )}
                  >
                    <Icon className={cn("size-3.5", isActive ? "text-primary" : config.color)} />
                    <span className="capitalize">{changeCase(cat, "camel_to_title")}</span>
                    {isActive && (
                      <Badge variant="default_light" className="ml-1 h-4 px-1 text-[9px] min-w-[1.25rem] justify-center bg-background/50">
                        {filteredAnnouncements.length}
                      </Badge>
                    )}
                  </Link>
                );
              })}
            </div>
          </div>
        </div>
      </div>

      <main className="max-w-3xl mx-auto px-4 py-8">
        {filteredAnnouncements.length === 0 ? (
          <div className="py-20 flex justify-center">
            <EmptyArea
              icons={[Megaphone]}
              title="All caught up!"
              description={`No announcements found in ${currentCategory}.`}
            />
          </div>
        ) : (
          <AnnouncementsList
            announcements={filteredAnnouncements}
            user={session?.user}
          />
        )}
      </main>
    </div>
  );
}
