// apps/platform/app/auth/reset-password/page.tsx
"use client";

import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { ButtonLink } from "@/components/utils/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, CheckCircle2, KeyRound, Loader2, Lock } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import * as z from "zod";
import { authClient } from "~/auth/client";

const ResetSchema = z
  .object({
    newPassword: z.string().min(8, "Must be at least 8 characters"),
    confirmNewPassword: z.string().min(8, "Must be at least 8 characters"),
  })
  .refine((data) => data.newPassword === data.confirmNewPassword, {
    message: "Passwords do not match",
    path: ["confirmNewPassword"],
  });

export default function ResetPassword() {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const searchParams = useSearchParams();
  const router = useRouter();
  const token = searchParams.get("token");

  const form = useForm<z.infer<typeof ResetSchema>>({
    resolver: zodResolver(ResetSchema),
    defaultValues: { newPassword: "", confirmNewPassword: "" },
  });

  async function onSubmit(data: z.infer<typeof ResetSchema>) {
    if (!token) {
      toast.error("Invalid or missing reset token.");
      return;
    }

    setIsSubmitting(true);
    try {
      const res = await authClient.resetPassword(
        {
          newPassword: data.newPassword,
          token,
        },
        { credentials: "include" }
      );

      if (res.error) {
        toast.error(res.error.message || "Failed to reset password");
        return;
      }

      toast.success("Password updated successfully!");
      router.push("/auth/sign-in");
    } catch (err) {
      toast.error("An unexpected error occurred.");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col items-center text-center space-y-2">
        <div className="p-3 rounded-xl bg-primary/5 text-primary mb-2 ring-1 ring-primary/10">
          <KeyRound className="size-6" />
        </div>
        <h1 className="text-2xl font-semibold tracking-tight">
          Set new password
        </h1>
        <p className="text-sm text-muted-foreground max-w-xs">
          Your new password must be different from previously used passwords.
        </p>
      </div>

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
          <FormField
            control={form.control}
            name="newPassword"
            render={({ field }) => (
              <FormItem>
                <FormLabel>New Password</FormLabel>
                <div className="relative">
                  <Lock className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                  <FormControl>
                    <Input
                      {...field}
                      type="password"
                      placeholder="••••••••"
                      className="pl-9"
                      disabled={isSubmitting}
                    />
                  </FormControl>
                </div>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="confirmNewPassword"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Confirm Password</FormLabel>
                <div className="relative">
                  <CheckCircle2 className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                  <FormControl>
                    <Input
                      {...field}
                      type="password"
                      placeholder="••••••••"
                      className="pl-9"
                      disabled={isSubmitting}
                    />
                  </FormControl>
                </div>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button type="submit" className="w-full" disabled={isSubmitting}>
            {isSubmitting ? (
              <>
                <Loader2 className="animate-spin" /> Resetting...
              </>
            ) : (
              "Reset Password"
            )}
          </Button>
        </form>
      </Form>

      <div className="flex justify-center">
        <ButtonLink
          variant="link"
          size="sm"
          className="text-muted-foreground"
          href="/auth/sign-in"
        >
          <ArrowLeft /> Back to Sign In
        </ButtonLink>
      </div>
    </div>
  );
}

// apps/platform-svelte/src/routes/auth/reset-password/+page.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Loader2, Lock } from 'lucide-svelte';
	import { toast } from 'svelte-sonner';
	import { authClient } from '$lib/auth-client';
	import { page } from '$app/state';
	import { goto } from '$app/navigation';

	let password = $state('');
	let confirm = $state('');
	let isLoading = $state(false);

	const token = $derived(page.url.searchParams.get('token') ?? '');

	async function onSubmit(e: Event) {
		e.preventDefault();
		if (password.length < 8) {
			toast.error('Password must be at least 8 characters');
			return;
		}
		if (password !== confirm) {
			toast.error('Passwords do not match');
			return;
		}
		if (!token) {
			toast.error('Invalid or missing reset token');
			return;
		}
		isLoading = true;
		try {
			await authClient.resetPassword({ newPassword: password, token });
			toast.success('Password reset successfully');
			goto('/auth/sign-in');
		} catch (e) {
			toast.error(e instanceof Error ? e.message : 'Failed to reset password');
		} finally {
			isLoading = false;
		}
	}
</script>

<svelte:head>
	<title>Reset Password | College Platform</title>
</svelte:head>

<div class="space-y-6">
	<div class="flex flex-col space-y-2 text-center">
		<h1 class="text-2xl font-semibold tracking-tight">Reset your password</h1>
		<p class="text-sm text-muted-foreground">Enter a new password for your account.</p>
	</div>

	<form class="space-y-4" onsubmit={onSubmit}>
		<div class="space-y-2">
			<Label for="new-password">New Password</Label>
			<div class="relative">
				<Lock class="absolute left-3 top-3 size-4 text-muted-foreground" />
				<Input
					id="new-password"
					type="password"
					bind:value={password}
					placeholder="••••••••"
					class="pl-9"
					autocomplete="new-password"
					disabled={isLoading}
					required
					minlength={8}
				/>
			</div>
		</div>

		<div class="space-y-2">
			<Label for="confirm">Confirm Password</Label>
			<div class="relative">
				<Lock class="absolute left-3 top-3 size-4 text-muted-foreground" />
				<Input
					id="confirm"
					type="password"
					bind:value={confirm}
					placeholder="••••••••"
					class="pl-9"
					autocomplete="new-password"
					disabled={isLoading}
					required
					minlength={8}
				/>
			</div>
		</div>

		<Button type="submit" class="w-full" disabled={isLoading}>
			{#if isLoading}
				<Loader2 class="mr-2 size-4 animate-spin" />
			{/if}
			Reset Password
		</Button>
	</form>
</div>
