// apps/platform/@/components/common/navbar.tsx
"use client";

import ProfileDropdown from "@/components/common/profile-dropdown";
import { Icon } from "@/components/icons";
import { ApplicationInfo } from "@/components/logo";
import { Button } from "@/components/ui/button";
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from "@/components/ui/command";
import { AuthButtonLink } from "@/components/utils/link";
import {
  NavLink,
  SUPPORT_LINKS,
  getNavLinks,
  socials,
} from "@/constants/links";
import { cn } from "@/lib/utils";
import { motion } from "framer-motion";
import {
  ArrowUpRight,
  LayoutDashboard,
  LogIn,
  Search,
  Settings,
  User
} from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import React, { useMemo, useState } from "react";
import type { Session } from "~/auth";
import { twUtility } from "../utils/tailwind-classes";
import { NavTabs } from "./nav-tabs";
import { ThemePopover, ThemeSwitcher } from "./theme-switcher";

const loggedInList = [
  { path: "/dashboard", title: "Dashboard", icon: LayoutDashboard },
  { path: "/dashboard/settings", title: "Settings", icon: Settings },
];

interface NavbarProps {
  user?: Session["user"];
}

export default function Navbar({ user }: NavbarProps) {
  const pathname = usePathname();
  const navLinks = getNavLinks(user);

  // Memoized categories logic
  const { categories } = useMemo(() => {
    const cats = ["all", ...new Set(navLinks.map((l) => l.category).filter(Boolean))];
    return { categories: cats };
  }, [navLinks]);

  const [activeCategory, setActiveCategory] = useState<string>("all");

  const availableLinks = useMemo(
    () => navLinks.filter((link) => activeCategory === "all" || link.category === activeCategory),
    [activeCategory, navLinks]
  );

  return (
    <header
      id="navbar"
      className={cn(
        "z-50 w-full transition-all duration-300",
        "bg-background/40 backdrop-blur-xl border-b border-border/40 supports-backdrop-filter:bg-background/30"
      )}
    >
      <div className="w-full max-w-(--max-app-width) mx-auto">

        <div className="flex items-center justify-between px-4 py-3 h-16">

          {/* Brand */}
          <Link href="/" className="flex items-center gap-2 transition-opacity hover:opacity-80">
            <ApplicationInfo />
          </Link>

          {/* Actions */}
          <div className="ml-auto flex items-center gap-2 sm:gap-3">
            <QuickLinks user={user} publicLinks={navLinks} />

            <div className="h-6 w-px bg-border/50 hidden sm:block mx-1" />

            <ThemeSwitcher />
            <ThemePopover className="hidden md:inline-flex" />

            {user ? (
              <ProfileDropdown user={user} />
            ) : (
              <AuthButtonLink
                size="sm"
                href={pathname}
                variant="rainbow"
                className="font-medium px-5"
              >
                Log In
              </AuthButtonLink>
            )}
          </div>
        </div>

        <div className="px-4 pb-0">
          <div className="flex flex-col gap-2">

            {categories.length > 1 && (
              <div className={cn("flex items-center gap-1 overflow-x-auto no-scrollbar py-1 -mx-4 px-4 mask-fade-sides", twUtility.horizontalScroll)}>
                {categories.map((category) => (
                  <button
                    key={category}
                    onClick={() => setActiveCategory(category)}
                    className={cn(
                      "relative px-3 py-1.5 text-xs font-medium capitalize transition-colors rounded-md whitespace-nowrap",
                      activeCategory === category
                        ? "text-primary"
                        : "text-muted-foreground hover:text-foreground hover:bg-muted/50"
                    )}
                  >
                    {category}
                    {activeCategory === category && (
                      <motion.div
                        layoutId="navbar-category-pill"
                        className="absolute inset-0 bg-primary/10 rounded-md -z-10"
                        transition={{ type: "spring", bounce: 0.2, duration: 0.6 }}
                      />
                    )}
                  </button>
                ))}
              </div>
            )}

            {/* Main Navigation Tabs */}
            <div className="pt-1 pb-1">
              <NavTabs
                key={activeCategory}
                navLinks={availableLinks.map((link) => ({
                  id: link.href,
                  href: link.href,
                  children: (
                    <span className="flex items-center gap-2">
                      {link.Icon && <link.Icon className="size-3.5 opacity-70" />}
                      {link.title}
                    </span>
                  ),
                  isNew: link.isNew,
                  items: link.items,
                }))}
              />
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}


interface QuickLinksProps extends NavbarProps {
  publicLinks: NavLink[];
}

export function QuickLinks({ user, publicLinks }: QuickLinksProps) {
  const [open, setOpen] = useState(false);
  const isLoggedIn = !!user;

  // Handle Ctrl/Cmd + K
  React.useEffect(() => {
    const down = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setOpen((open) => !open);
      }
    };
    document.addEventListener("keydown", down);
    return () => document.removeEventListener("keydown", down);
  }, []);

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="hidden md:flex items-center w-56 h-9 px-3 rounded-lg border border-border/80 bg-card/80 hover:bg-card hover:border-border transition-all text-sm text-muted-foreground group"
      >
        <Search className="size-3.5 mr-2 opacity-50 group-hover:opacity-100 transition-opacity" />
        <span className="flex-1 text-left">Search...</span>
        <kbd className="pointer-events-none inline-flex h-5 select-none items-center gap-1 rounded border bg-muted px-1.5 font-mono text-[10px] font-medium text-muted-foreground opacity-100">
          <span className="text-xs">⌘</span>K
        </kbd>
      </button>

      <Button
        onClick={() => setOpen(true)}
        size="icon_sm"
        variant="ghost"
        className="md:hidden text-muted-foreground"
      >
        <Search className="size-5" />
      </Button>

      <CommandDialog open={open} onOpenChange={setOpen} title="Search Ecosystem" description="Search through the college ecosystem">
        <CommandInput placeholder="Type to search ecosystem..." />
        <CommandList>
          <CommandEmpty>No results found.</CommandEmpty>

          <CommandGroup heading="Suggestions">
            {publicLinks.map((item, index) => (
              <CommandItem key={`cmd-${index}`} asChild>
                <Link
                  href={item.href}
                  onClick={() => setOpen(false)}
                  className="flex items-center justify-between group cursor-pointer"
                >
                  <div className="flex items-center">
                    {item.Icon ? <item.Icon className="mr-3 size-4 text-muted-foreground group-hover:text-primary transition-colors" /> : <ArrowUpRight className="mr-3 size-4" />}
                    <div className="flex flex-col">
                      <span className="font-medium">{item.title}</span>
                      {item.description && <span className="text-xs text-muted-foreground font-normal line-clamp-1">{item.description}</span>}
                    </div>
                  </div>
                  <ArrowUpRight className="size-3 opacity-0 group-hover:opacity-50 -translate-x-2 group-hover:translate-x-0 transition-all" />
                </Link>
              </CommandItem>
            ))}
          </CommandGroup>

          <CommandSeparator className="my-2" />

          {isLoggedIn ? (
            <CommandGroup heading="Account">
              <CommandItem onSelect={() => setOpen(false)}>
                <Link href={`/u/${user.username}`} className="flex items-center w-full">
                  <User className="mr-2 size-4" /> Profile
                </Link>
              </CommandItem>
              {loggedInList.map((item, i) => (
                <CommandItem key={i} onSelect={() => setOpen(false)}>
                  <Link href={item.path} className="flex items-center w-full">
                    <item.icon className="mr-2 size-4" /> {item.title}
                  </Link>
                </CommandItem>
              ))}
            </CommandGroup>
          ) : (
            <CommandGroup heading="Authentication">
              <CommandItem onSelect={() => setOpen(false)}>
                <Link href="/auth/sign-in" className="flex items-center w-full">
                  <LogIn className="mr-2 size-4" /> Sign In
                </Link>
              </CommandItem>
            </CommandGroup>
          )}
        </CommandList>
      </CommandDialog>
    </>
  );
}

// --- UTILITY COMPONENTS ---

export function SocialBar({ className }: { className?: string }) {
  if (socials.length === 0) return null;
  return (
    <div className={cn("flex items-center gap-1", className)}>
      {socials.map((link) => (
        <Link
          key={link.href}
          href={link.href}
          target="_blank"
          className={cn(
            "flex items-center justify-center size-8 rounded-full text-muted-foreground transition-all",
            "hover:bg-primary/10 hover:text-primary hover:scale-105"
          )}
        >
          <link.icon className="size-4" />
        </Link>
      ))}
    </div>
  );
}

export function SupportBar() {
  return (
    <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
      {SUPPORT_LINKS.map((link) => (
        <Link
          key={link.href}
          href={link.href}
          className="group flex items-center gap-1.5 text-xs font-medium text-muted-foreground hover:text-primary transition-colors"
        >
          {link.title}
          <ArrowUpRight className="size-3 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
        </Link>
      ))}
    </div>
  );
}
export function GoToTopButton({ className }: { className?: string }) {
  const handleClick = () => {
    window?.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <Button
      variant="ghost"
      size="sm"
      className={cn("text-xs text-muted-foreground hover:text-foreground", className)}
      onClick={handleClick}
    >
      Back to Top <Icon name="arrow-up" />
    </Button>
  );
}

// apps/platform-svelte/src/lib/components/common/navbar/navbar.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';

  import { Button } from '$lib/components/ui/button';
  import * as Command from '$lib/components/ui/command';
  import * as Dialog from '$lib/components/ui/dialog';

  import { LogIn, Search, User } from 'lucide-svelte';

  import ProfileDropdown from '$lib/components/common/profile-dropdown.svelte';
  import ThemePopover from '$lib/components/common/theme-popover.svelte';
  import ThemeSwitcher from '$lib/components/common/theme-switcher.svelte';
  import NavTabs from './nav-tabs.svelte';

  import { getNavLinks } from '$lib/config/nav';

  let { user } = $props();

  let open = $state(false);
  let search = $state('');
  let activeCategory = $state('all');

  let navLinks = $derived(getNavLinks(user));

  let categories =  $derived([
    'all',
    ...new Set(navLinks.map((l) => l.category).filter(Boolean))
  ]);

  let filteredLinks = $derived(
    activeCategory === 'all'
      ? navLinks
      : navLinks.filter((l) => l.category === activeCategory)
  );

  let filteredSearch = $derived(	
    search.length === 0
      ? navLinks
      : navLinks.filter((l) =>
          `${l.title} ${l.description ?? ''} ${l.category ?? ''}`
            .toLowerCase()
            .includes(search.toLowerCase())
        ))

  const navigate = (href: string) => {
    open = false;
    goto(href);
  };

  // Cmd + K
  onMount(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        open = !open;
      }
    };

    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  });
</script>

<header class="z-50 w-full border-b border-border/40 bg-background/40 backdrop-blur-xl">
	<div class="mx-auto flex h-16 max-w-[--max-app-width] items-center justify-between px-4 py-3">
		<!-- Brand -->
		<a href="/" class="flex items-center gap-2 hover:opacity-80">
			<slot name="logo" />
		</a>

		<!-- Actions -->
		<div class="flex items-center gap-3">
			<!-- Search Trigger -->
			<Button
				variant="outline"
				class="hidden w-56 justify-start text-muted-foreground md:flex"
				on:click={() => (open = true)}
			>
				<Search class="mr-2 size-4" />
				Search...
				<span class="ml-auto text-xs opacity-60">⌘K</span>
			</Button>

			<ThemeSwitcher />
			<ThemePopover />

			{#if user}
				<ProfileDropdown {user} />
			{:else}
				<Button on:click={() => goto('/auth/sign-in')}>
					<LogIn class="mr-2 size-4" />
					Log In
				</Button>
			{/if}
		</div>
	</div>

	<!-- Categories -->
	{#if categories.length > 1}
		<div class="flex gap-2 overflow-x-auto px-4">
			{#each categories as category}
				<Button
					size="sm"
					variant={activeCategory === category ? 'default' : 'ghost'}
					on:click={() => (activeCategory = category)}
					class="capitalize"
				>
					{category}
				</Button>
			{/each}
		</div>
	{/if}

	<!-- Tabs -->
	<div class="px-4 py-2">
		<NavTabs {filteredLinks} />
	</div>
</header>

<!-- ✅ shadcn Command Dialog -->
<Dialog.Root bind:open>
	<Dialog.Content class="overflow-hidden p-0">
		<Command.Root>
			<Command.Input bind:value={search} placeholder="Search ecosystem..." />

			<Command.List>
				<Command.Empty>No results found.</Command.Empty>

				<!-- Pages -->
				<Command.Group heading="Pages">
					{#each filteredSearch as item}
						<Command.Item value={item.title} onSelect={() => navigate(item.href)}>
							{#if item.Icon}
								<svelte:component this={item.Icon} class="mr-2 size-4" />
							{/if}

							<div class="flex flex-col">
								<span>{item.title}</span>
								{#if item.description}
									<span class="text-xs text-muted-foreground">
										{item.description}
									</span>
								{/if}
							</div>
						</Command.Item>
					{/each}
				</Command.Group>

				<!-- Auth / Account -->
				<Command.Group heading="Account">
					{#if user}
						<Command.Item onSelect={() => navigate(`/u/${user.username}`)}>
							<User class="mr-2 size-4" />
							Profile
						</Command.Item>
					{:else}
						<Command.Item onSelect={() => navigate('/auth/sign-in')}>
							<LogIn class="mr-2 size-4" />
							Sign In
						</Command.Item>
					{/if}
				</Command.Group>
			</Command.List>
		</Command.Root>
	</Dialog.Content>
</Dialog.Root>
