// apps/platform-svelte/src/lib/components/common/not-found.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { ArrowLeft, Home } from 'lucide-svelte';
</script>

<div class="flex min-h-[60vh] flex-col items-center justify-center px-4 text-center">
	<div class="relative mb-8">
		<span
			class="select-none text-[10rem] font-black leading-none tracking-tighter text-muted-foreground/10 sm:text-[14rem]"
		>
			404
		</span>
		<h1
			class="absolute inset-0 flex items-center justify-center text-3xl font-bold tracking-tight text-foreground sm:text-4xl"
		>
			Page Not Found
		</h1>
	</div>
	<p class="mb-8 max-w-md text-muted-foreground">
		The page you are looking for does not exist or has been moved. Please check the URL or navigate
		back to a known page.
	</p>
	<div class="flex items-center gap-3">
		<Button variant="outline" href="/">
			<Home class="size-4" />
			Go Home
		</Button>
		<Button
			variant="ghost"
			onclick={() => history.back()}
		>
			<ArrowLeft class="size-4" />
			Go Back
		</Button>
	</div>
</div>

// apps/platform/app/(common)/(academics)/results/[rollNo]/not-found.tsx
import { TiltedChip } from "@/components/site/sections";
import { ButtonLink } from "@/components/utils/link";
import { Search } from "lucide-react";
import type { Metadata } from "next";
import { RecoverySteps } from "./recovery-steps";

export const metadata: Metadata = {
  title: "Result Not Found",
  description: "The result you are looking for does not exist.",
};

export default function NotFound() {
  return (
    <div className="mx-auto flex w-full max-w-3xl flex-col gap-8 px-4 py-16">
      <div className="flex flex-col items-start">
        <TiltedChip>Not found</TiltedChip>
        <h1 className="mt-4 text-balance text-heading-lg font-medium text-foreground md:text-display">
          No result for
          <br />
          <span className="text-primary">this roll number</span>
        </h1>
        <p className="mt-3 text-pretty text-body text-muted-foreground md:text-body-lg">
          Check the roll number, or fetch the result from the college site.
        </p>
        <div className="mt-6">
          <ButtonLink href="/results" variant="primary">
            <Search />
            Search results
          </ButtonLink>
        </div>
      </div>
      <RecoverySteps />
    </div>
  );
}
