// apps/platform/app/(common)/(community)/polls/page.tsx
import EmptyArea from "@/components/common/empty-area";
import { Tabs, TabsContent, VercelTabsList } from "@/components/ui/tabs";
import {
  getClosedPolls,
  getOpenPolls,
  getPollsCreatedByLoggedInUser,
} from "~//actions/common.poll";
import type { PollType } from "~/models/poll";
import CreatePoll from "./components/create-poll";
import PollComponent from "./components/poll-component";

import AdUnit from "@/components/common/adsense";
import { Badge } from "@/components/ui/badge";
import { AuthButtonLink } from "@/components/utils/link";
import { LogIn } from "lucide-react";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { CgPoll } from "react-icons/cg";
import { auth } from "~/auth";

export const metadata: Metadata = {
  title: `Polls`,
  description: "Check the latest polls here.",
  alternates: {
    canonical: "/polls",
  },
  keywords: [
    "NITH",
    "Polls",
    "NITH Polls",
    "NITH Polling",
    "NITH Voting",
    "NITH Community Polls",
    "NITH Community Voting",
    "NITH Student Polls",
    "NITH Student Voting",
  ],
};

const tabs = [
  { label: "Open Polls", id: "opened-polls" },
  { label: "Closed Polls", id: "closed-polls" },
  { label: "Your Polls", id: "your-polls" },
];

export default async function PollsPage(props: {
  searchParams: Promise<{
    tab?: string;
  }>;
}) {
  const searchParams = await props.searchParams;
  const activeTab = searchParams.tab || "opened-polls";

  const headersList = await headers();
  const session = await auth.api.getSession({
    headers: headersList,
  });

  const polls = await Promise.all([
    getOpenPolls(),
    getClosedPolls(),
    session?.user ? getPollsCreatedByLoggedInUser() : Promise.resolve([]),
  ]);

  return (
    <div className="container max-w-6xl mx-auto px-4 md:px-6 py-6 md:py-8">
      <Tabs defaultValue={activeTab} className="w-full space-y-6">
        <VercelTabsList tabs={tabs} onTabChangeQuery="tab" />

        {tabs.map((tab, idx) => {
          if (tab.id === "your-polls" && !session?.user) {
            return (
              <TabsContent value={tab.id} key={tab.id} className="mt-0">
                <EmptyArea
                  title="Your Polls"
                  description="Sign in to create and manage your own polls."
                  actionProps={{
                    asChild: true,
                    variant: "raw",
                    children: (
                      <AuthButtonLink
                        authorized={!!session?.user}
                        variant="rainbow"
                        size="sm"
                        href="/polls?tab=opened-polls"
                      >
                        <LogIn />
                        Sign In
                      </AuthButtonLink>
                    ),
                  }}
                />
              </TabsContent>
            );
          }

          return (
            <TabsContent value={tab.id} key={tab.id} className="mt-0 space-y-6">
              <div className="sticky top-20 z-30 flex items-center justify-between h-12 px-4 bg-card/95 backdrop-blur supports-backdrop-filter:bg-card/80 border rounded-lg">
                <div className="flex items-center gap-2">
                  <CgPoll className="size-4 text-muted-foreground" />
                  <h2 className="text-sm font-semibold">{tab.label}</h2>
                  <Badge variant="secondary" className="ml-1">
                    {polls[idx].length}
                  </Badge>
                </div>
                {tab.id === "your-polls" && <CreatePoll />}
              </div>

              {polls[idx].length === 0 ? (
                <EmptyArea
                  title={`No ${tab.label.toLowerCase()}`}
                  description={`There are no ${tab.label.toLowerCase()} at the moment.`}
                />
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 @container">
                  {polls[idx].map((poll: PollType) => (
                    <PollComponent
                      poll={poll}
                      key={poll._id}
                      user={session?.user}
                    />
                  ))}
                </div>
              )}
            </TabsContent>
          );
        })}

        <div className="pt-4">
          <AdUnit adSlot="display-horizontal" key="polls-page-ad" />
        </div>
      </Tabs>
    </div>
  );
}

// apps/platform-svelte/src/routes/polls/+page.svelte
<script lang="ts">
	import type { PageProps } from './$types';
	import { Card, CardContent, CardHeader, CardTitle } from '$lib/components/ui/card';
	import { Badge } from '$lib/components/ui/badge';
	import StaggerContainer from '$lib/components/animation/stagger-container.svelte';
	import InView from '$lib/components/animation/in-view.svelte';
	import EmptyArea from '$lib/components/common/empty-area.svelte';
	import { Vote, Clock } from 'lucide-svelte';

	let { data }: PageProps = $props();
	const polls = $derived(data.polls);

	const openPolls = $derived(
		polls.filter((p) => p.closesAt && new Date(p.closesAt) > new Date())
	);
	const closedPolls = $derived(
		polls.filter((p) => !p.closesAt || new Date(p.closesAt) <= new Date())
	);
</script>

<svelte:head>
	<title>Polls | College Platform</title>
</svelte:head>

<main class="mx-auto w-full max-w-4xl space-y-8 px-4 py-10 md:px-6">
	<InView variant="fly-up">
		<div class="space-y-2">
			<div
				class="inline-flex items-center gap-2 rounded-full border border-border/50 bg-muted/40 px-3 py-1 text-xs font-medium text-muted-foreground"
			>
				<Vote class="size-3.5 text-primary" />
				Campus Voting
			</div>
			<h1 class="text-3xl font-bold tracking-tight md:text-4xl">Polls</h1>
			<p class="text-muted-foreground">Cast your vote on campus opinions and surveys.</p>
		</div>
	</InView>

	{#if polls.length === 0}
		<EmptyArea title="No polls yet" description="Check back later for new polls." />
	{:else}
		{#if openPolls.length > 0}
			<section class="space-y-4">
				<h2 class="text-lg font-semibold">Open Polls</h2>
				<StaggerContainer class="grid grid-cols-1 gap-4 md:grid-cols-2">
					{#each openPolls as poll (poll._id)}
						<a href={`/polls/${poll._id}`}>
							<Card class="h-full transition-all hover:-translate-y-0.5 hover:shadow-md">
								<CardHeader>
									<div class="flex items-start justify-between gap-3">
										<CardTitle class="text-base">{poll.question}</CardTitle>
										<Badge variant="default" class="shrink-0 text-[10px]">Open</Badge>
									</div>
								</CardHeader>
								<CardContent>
									<div class="flex items-center justify-between text-xs text-muted-foreground">
										<span>{poll.votes?.length ?? 0} votes</span>
										{#if poll.closesAt}
											<span class="inline-flex items-center gap-1">
												<Clock class="size-3" />
												Closes {new Date(poll.closesAt).toLocaleDateString()}
											</span>
										{/if}
									</div>
								</CardContent>
							</Card>
						</a>
					{/each}
				</StaggerContainer>
			</section>
		{/if}

		{#if closedPolls.length > 0}
			<section class="space-y-4">
				<h2 class="text-lg font-semibold text-muted-foreground">Closed Polls</h2>
				<StaggerContainer class="grid grid-cols-1 gap-4 md:grid-cols-2">
					{#each closedPolls as poll (poll._id)}
						<a href={`/polls/${poll._id}`}>
							<Card class="h-full opacity-80 transition-all hover:-translate-y-0.5 hover:opacity-100">
								<CardHeader>
									<div class="flex items-start justify-between gap-3">
										<CardTitle class="text-base">{poll.question}</CardTitle>
										<Badge variant="secondary" class="shrink-0 text-[10px]">Closed</Badge>
									</div>
								</CardHeader>
								<CardContent>
									<div class="text-xs text-muted-foreground">
										{poll.votes?.length ?? 0} total votes
									</div>
								</CardContent>
							</Card>
						</a>
					{/each}
				</StaggerContainer>
			</section>
		{/if}
	{/if}
</main>
