// apps/platform/@/components/common/header-bar.tsx
import { Separator } from "@/components/ui/separator"; // Assuming you have shadcn separator
import { cn } from "@/lib/utils";
import React from "react";

export type HeaderBarProps = {
  Icon?: React.ComponentType<React.SVGProps<SVGSVGElement>>;
  titleNode: React.ReactNode;
  descriptionNode: React.ReactNode;
  actionNode?: React.ReactNode;
  className?: string;
  hideSeparator?: boolean;
};

export function HeaderBar({
  Icon,
  titleNode,
  descriptionNode,
  actionNode,
  className,
  hideSeparator = false,
}: HeaderBarProps) {
  return (
    <div className={cn("w-full space-y-4 z-1", className)}>
      <div className="flex items-start justify-between">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            {Icon && <Icon className="size-5 text-primary/80" />}
            <h1 className="text-2xl font-bold tracking-tight text-foreground">
              {titleNode}
            </h1>
          </div>
          <p className="text-sm text-muted-foreground max-w-2xl">
            {descriptionNode}
          </p>
        </div>
        {actionNode && <div className="ml-4">{actionNode}</div>}
      </div>
      {!hideSeparator && <Separator className="my-4" />}
    </div>
  );
}

// apps/platform-svelte/src/lib/components/common/header-bar.svelte
<script lang="ts">
	import { cn } from '$lib/utils.js';
	import { Separator } from '$lib/components/ui/separator';
	import type { Snippet } from 'svelte';

	let {
		title,
		description = '',
		hideSeparator = false,
		class: className = '',
		icon,
		action
	}: {
		title: string;
		description?: string;
		hideSeparator?: boolean;
		class?: string;
		icon?: Snippet;
		action?: Snippet;
	} = $props();
</script>

<div class={cn('space-y-4', className)}>
	<div class="flex items-start justify-between gap-4">
		<div class="flex items-start gap-3">
			{#if icon}
				<div class="mt-0.5 flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
					{@render icon()}
				</div>
			{/if}
			<div class="space-y-1">
				<h1 class="text-2xl font-bold tracking-tight text-foreground">{title}</h1>
				{#if description}
					<p class="text-sm text-muted-foreground">{description}</p>
				{/if}
			</div>
		</div>
		{#if action}
			<div class="shrink-0">
				{@render action()}
			</div>
		{/if}
	</div>
	{#if !hideSeparator}
		<Separator />
	{/if}
</div>
