// apps/platform/app/[moderator]/(higher_roles)/schedules/page.tsx
import { ResponsiveContainer } from "@/components/common/container";
import EmptyArea from "@/components/common/empty-area";
import { HeaderBar } from "@/components/common/header-bar";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/utils/link";
import { cn } from "@/lib/utils";
import { formatDistanceToNow } from "date-fns";
import {
  ArrowUpRight,
  Calendar,
  CalendarDays,
  Clock,
  Layers,
  Plus,
  Settings2
} from "lucide-react";
import Link from "next/link";
import { getAllTimeTables } from "~//actions/common.time-table";
import { TimeTableWithID } from "~/models/time-table";

export default async function Schedules(props: {
  params: Promise<{
    moderator: string;
  }>;
}) {
  const timetables = await getAllTimeTables();
  const params = await props.params;

  return (
    <div className="min-h-screen bg-background pb-20">
      <HeaderBar
        Icon={CalendarDays}
        titleNode={
          <div className="flex items-center gap-3">
            <span>Manage Timetables</span>
            <Badge variant="default" className="px-2 h-6 rounded-md text-xs font-mono">
              {timetables.length}
            </Badge>
          </div>
        }
        descriptionNode="Configure academic schedules, manage sections, and publish updates."
        actionNode={
          <ButtonLink
            variant="default"
            size="sm"
            effect="shineHover"
            href={`/${params.moderator}/schedules/create`}
            className="h-9 px-4 shadow-md shadow-primary/20"
          >
            <Plus className="mr-2 size-4" />
            Create Schedule
          </ButtonLink>
        }
      />

      {timetables.length === 0 ? (
        <div className="mt-8 px-4">
            <EmptyArea
            title="No Timetables Configured"
            description="Get started by creating a master schedule for a specific year and department."
            icons={[Calendar, Layers, Plus]}
            actionProps={{
                variant: "outline",
                href: `/${params.moderator}/schedules/create`,
                className: cn("mt-4"),
                children: (<>
                    <Plus className="mr-2 size-4" /> Create First Timetable
                </>),
            }}
            />
        </div>
      ) : (
        <ResponsiveContainer className="mt-8">
            {timetables.map((timetable, i) => {
              // Construct the view URL
              const href = `/${params.moderator}/schedules/${timetable.department_code}/${timetable.year}/${timetable.semester}`;
              
              return (
                <TimetableCard 
                    key={timetable._id} 
                    timetable={timetable} 
                    href={href} 
                    index={i} 
                />
              );
            })}
        </ResponsiveContainer>
      )}
    </div>
  );
}


function TimetableCard({ timetable, href, index }: { timetable: Partial<TimeTableWithID>, href: string, index: number }) {
    return (
        <Link
            href={href}
            className="group relative flex flex-col justify-between rounded-xl border border-border/50 bg-card p-5 transition-all duration-300 hover:border-primary/40 hover:shadow-lg hover:shadow-primary/5 hover:-translate-y-1"
            style={{ animationDelay: `${index * 100}ms` }}
        >
            {/* Header: Icon & Title */}
            <div className="flex items-start justify-between mb-6">
                <div className="flex items-center gap-4">
                    <div className="flex size-10 shrink-0 items-center justify-center rounded-lg border bg-muted/50 text-muted-foreground group-hover:border-primary/20 group-hover:bg-primary/10 group-hover:text-primary transition-colors">
                        <Calendar className="size-5" />
                    </div>
                    <div>
                        <h3 className="font-semibold text-lg leading-tight group-hover:text-primary transition-colors">
                            {timetable.sectionName || "Untitled Section"}
                        </h3>
                        <p className="text-xs text-muted-foreground mt-1 font-mono">
                            {timetable.department_code}
                        </p>
                    </div>
                </div>
                
                {/* Edit Action */}
                <div className="opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all duration-300">
                    <div className="p-2 rounded-full bg-muted/50 text-muted-foreground hover:bg-primary/10 hover:text-primary">
                        <Settings2 className="size-4" />
                    </div>
                </div>
            </div>

            {/* Body: Metadata Chips */}
            <div className="flex flex-wrap gap-2 mb-6">
                <Badge variant="outline" className="rounded-md px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider bg-background/50 text-muted-foreground border-border/60">
                    Year {timetable.year}
                </Badge>
                <div className="w-px h-5 bg-border/60" />
                <Badge variant="outline" className="rounded-md px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider bg-background/50 text-muted-foreground border-border/60">
                    Sem {timetable.semester}
                </Badge>
            </div>

            {/* Footer: Timestamp & Action */}
            <div className="flex items-center justify-between pt-4 border-t border-border/40">
                <div className="flex items-center gap-1.5 text-xs text-muted-foreground/60">
                    <Clock className="size-3" />
                    <span>
                        Updated {formatDistanceToNow(new Date(timetable.updatedAt || new Date()), { addSuffix: true })}
                    </span>
                </div>
                
                <div className="flex items-center gap-1 text-xs font-medium text-primary opacity-0 group-hover:opacity-100 transition-opacity">
                    View Details <ArrowUpRight className="size-3" />
                </div>
            </div>
        </Link>
    );
}

// apps/platform-svelte/src/routes/schedules/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import { Badge } from '$lib/components/ui/badge';
	import { Separator } from '$lib/components/ui/separator';
	import StaggerContainer from '$lib/components/animation/stagger-container.svelte';
	import InView from '$lib/components/animation/in-view.svelte';
	import EmptyArea from '$lib/components/common/empty-area.svelte';
	import { CalendarRange, GraduationCap, Layers, LayoutGrid } from 'lucide-svelte';
	import { getDepartmentShort } from '$lib/constants/core.departments';

	let { data }: { data: PageData } = $props();
	const timeTables = $derived(data.timeTables);
</script>

<svelte:head>
	<title>Timetables | College Platform</title>
	<meta
		name="description"
		content="Browse and access academic schedules across departments."
	/>
</svelte:head>

<main class="relative min-h-screen pb-20">
	<div
		class="pointer-events-none absolute inset-0 -z-10 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-size-[24px_24px] mask-[radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)]"
	></div>

	<InView variant="fly-up">
		<section
			class="mx-auto flex max-w-(--max-app-width) flex-col items-center gap-4 px-4 pb-12 pt-20 text-center md:px-6"
		>
			<Badge
				variant="outline"
				class="rounded-full border-primary/20 bg-primary/5 px-4 py-1 text-xs font-medium uppercase tracking-wider text-primary"
			>
				<CalendarRange class="mr-2 size-3" /> Academic Schedule
			</Badge>
			<h1 class="text-4xl font-bold tracking-tight md:text-5xl">
				Find Your <span class="text-primary">Timetable</span>
			</h1>
			<p class="max-w-2xl text-sm text-muted-foreground md:text-base">
				Access the latest academic schedules. Filter by department, year, or semester to find your
				section.
			</p>
		</section>
	</InView>

	<div class="mx-auto max-w-7xl px-4 md:px-6">
		<div class="flex items-center justify-between py-6">
			<div class="flex items-center gap-2 text-sm text-muted-foreground">
				<LayoutGrid class="size-4" />
				<span>
					Viewing <strong>{timeTables.length}</strong> active schedules
				</span>
			</div>
			<Separator class="ml-4 mr-2 max-w-25 flex-1 opacity-50" />
		</div>

		{#if timeTables.length === 0}
			<div class="rounded-xl border border-dashed bg-muted/20 py-20">
				<EmptyArea
					title="No Timetables Found"
					description="There are no active timetables matching your criteria at the moment."
				/>
			</div>
		{:else}
			<StaggerContainer
				class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
			>
				{#each timeTables as timetable (timetable._id)}
					{@const deptShort = getDepartmentShort(timetable.department_code as string)}
					<a
						href={`/schedules/${timetable.department_code}/${timetable.year}/${timetable.semester}`}
						class="group relative flex flex-col justify-between rounded-xl border border-border/50 bg-card p-5 transition-all duration-300 hover:-translate-y-1 hover:border-primary/50 hover:shadow-lg hover:shadow-primary/5"
					>
						<div class="mb-4 flex items-start justify-between">
							<Badge
								variant="secondary"
								class="bg-muted font-mono text-[10px] uppercase tracking-wider text-muted-foreground transition-colors group-hover:bg-primary/10 group-hover:text-primary"
							>
								{deptShort || timetable.department_code}
							</Badge>

							<div
								class="flex size-8 items-center justify-center rounded-lg border border-border bg-background text-muted-foreground shadow-sm transition-all group-hover:border-primary/30 group-hover:text-primary"
							>
								<CalendarRange class="size-4" />
							</div>
						</div>

						<div class="mb-6">
							<h3
								class="line-clamp-1 text-lg font-bold text-foreground transition-colors group-hover:text-primary"
							>
								{timetable.sectionName}
							</h3>
							<p class="mt-1 text-xs text-muted-foreground">
								{timetable.department_code} Department
							</p>
						</div>

						<div class="mt-auto grid grid-cols-2 gap-2">
							<div
								class="flex items-center gap-2 rounded-md border border-transparent bg-muted/40 px-2 py-1.5 transition-colors group-hover:border-border/50"
							>
								<GraduationCap class="size-3.5 text-muted-foreground" />
								<span class="text-xs font-medium">Year {timetable.year}</span>
							</div>
							<div
								class="flex items-center gap-2 rounded-md border border-transparent bg-muted/40 px-2 py-1.5 transition-colors group-hover:border-border/50"
							>
								<Layers class="size-3.5 text-muted-foreground" />
								<span class="text-xs font-medium">Sem {timetable.semester}</span>
							</div>
						</div>
					</a>
				{/each}
			</StaggerContainer>
		{/if}
	</div>
</main>
