// apps/platform-svelte/src/lib/components/common/footer.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import ApplicationInfo from '$lib/components/common/application-info.svelte';
	import { appConfig, supportLinks } from '$lib/config/project';
	import { ArrowUpRight } from 'lucide-svelte';

	const aboutLinks = [
		{ title: 'About', href: '/about' },
		{ title: 'Contact', href: '/contact' },
		{ title: 'Privacy Policy', href: '/privacy-policy' },
		{ title: 'Terms', href: '/terms' }
	] as const;
</script>

<footer class="border-t border-border/40 bg-background pt-14 pb-8 lg:pt-20">
	<div class="mx-auto grid w-full max-w-(--max-app-width) gap-10 px-4 lg:grid-cols-3">
		<div class="space-y-4">
			<a href={resolve('/')} class="transition-opacity hover:opacity-80"><ApplicationInfo /></a>
			<p class="max-w-xs text-sm text-muted-foreground">{appConfig.description}</p>
		</div>

		<div>
			<h3 class="mb-4 text-sm font-semibold">Community</h3>
			<ul class="space-y-2">
				{#each supportLinks as link (link.href)}
					<li>
						<a
							href={link.href}
							rel="external noreferrer noopener"
							class="inline-flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-primary"
						>
							{link.title}
							<ArrowUpRight class="size-3.5" />
						</a>
					</li>
				{/each}
			</ul>
		</div>

		<div>
			<h3 class="mb-4 text-sm font-semibold">About & Legal</h3>
			<ul class="space-y-2">
				{#each aboutLinks as link (link.href)}
					<li>
						<a
							href={resolve(link.href)}
							class="text-sm text-muted-foreground transition-colors hover:text-primary"
						>
							{link.title}
						</a>
					</li>
				{/each}
			</ul>
		</div>
	</div>

	<div
		class="mx-auto mt-10 flex w-full max-w-(--max-app-width) items-center justify-between gap-3 border-t border-border/40 px-4 pt-6"
	>
		<p class="text-xs text-muted-foreground">
			© {new Date().getFullYear()}
			{appConfig.name}. All rights reserved.
		</p>
		<a
			href={appConfig.githubRepo}
			target="_blank"
			rel="external noreferrer noopener"
			class="text-xs text-muted-foreground hover:text-primary"
		>
			GitHub
		</a>
	</div>
</footer>

// apps/platform/@/components/common/footer.tsx
import { GoToTopButton, SocialBar } from "@/components/common/navbar";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { appConfig, supportLinks } from "~/project.config";
import { ApplicationInfo } from "../logo";
import GithubStars from "./github";
import { ThemePopover, ThemeSwitcher } from "./theme-switcher";

const sectionLinks = [
  {
    title: "Support",
    links: supportLinks,
  },
  {
    title: "About",
    links: [
      { title: "About Us", href: "/about" },
      {
        href: "/contact",
        title: "Contact us",
      },
      {
        href: "/privacy-policy",
        title: "Privacy Policy",
      },
      {
        href: "/terms",
        title: "Terms of Service",
      },
    ],
  },
];

export default async function Footer() {
  return (
    <footer
      className={cn(
        "z-40 w-full transition-all pt-5 pb-8 mt-auto",
        "bg-card border-b"
      )}
    >
      <div className="w-full max-w-(--max-app-width) mx-auto px-3 sm:px-6 lg:px-8">
        <div className="grid w-full grid-cols-10 gap-10 lg:flex-row lg:items-start lg:text-left">
          <div className="flex w-full col-span-10 md:col-span-6 flex-col justify-between gap-6 lg:items-start">
            {/* Logo */}
            <div className="flex items-center gap-2 lg:justify-start">
              <Link href="/">
                <ApplicationInfo />
              </Link>
            </div>
            <p className="text-pretty text-sm text-muted-foreground">
              {appConfig.description}
            </p>
            <div>
              <GithubStars />
            </div>
            <SocialBar className="ml-0 my-2" />
          </div>
          <div className="grid w-full gap-6 col-span-10 md:col-span-4 grid-cols-2 sm:grid-cols-2 lg:gap-20 lg:ml-auto justify-end">
            {sectionLinks.map((section, sectionIdx) => (
              <div key={sectionIdx}>
                <h3 className="mb-4 font-semibold text-sm">{section.title}</h3>
                <ul className="space-y-3 text-xs text-muted-foreground">
                  {section.links.map((link, linkIdx) => (
                    <li
                      key={linkIdx}
                      className="font-medium hover:text-primary"
                    >
                      <a href={link.href}>{link.title}</a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
        <div className="mt-8 flex flex-col justify-between gap-4 border-t py-8 text-xs font-medium text-muted-foreground md:flex-row md:items-center md:text-left">
          <p className="order-2 lg:order-1">
            © {new Date().getFullYear()} {appConfig.name}. All rights reserved.
          </p>
          {/* <ul className="order-1 flex flex-col gap-2 md:order-2 md:flex-row">
            {productLinks.links.map((link, idx) => (
              <li key={idx} className="hover:text-primary">
                <a href={link.href}> {link.title}</a>
              </li>
            ))}
          </ul> */}
          <div className="order-1 md:order-2 flex items-center gap-2">
            <ThemeSwitcher />
            <ThemePopover className="md:hidden" />
            <GoToTopButton />
          </div>
        </div>
      </div>
    </footer>
  );
}
