// apps/platform-svelte/src/routes/results/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import ResultCard from '$lib/components/application/result/result-card.svelte';
	import ResultSearch from '$lib/components/application/result/result-search.svelte';
	import ResultPagination from '$lib/components/application/result/result-pagination.svelte';
	import StaggerContainer from '$lib/components/animation/stagger-container.svelte';
	import InView from '$lib/components/animation/in-view.svelte';
	import EmptyArea from '$lib/components/common/empty-area.svelte';
	import { Sparkles, TrendingUp } from 'lucide-svelte';
	import { orgConfig, appConfig } from '$lib/config/project';

	let { data }: { data: PageData } = $props();

	const resultsData = $derived(data.resultsData);
	const labels = $derived(data.labels);
	const currentPage = $derived(data.page);
</script>

<svelte:head>
	<title>{orgConfig.shortName} Results Portal - Check Semester Results Online</title>
	<meta
		name="description"
		content={`${orgConfig.shortName} result portal. Search semester results by roll number, name, or course. Access academic records, grades, and transcripts for all programs.`}
	/>
	<link rel="canonical" href={`${appConfig.url}/results`} />
</svelte:head>

<main
	class="@container mx-auto flex w-full max-w-(--max-app-width) flex-col gap-8 px-4 py-10 md:px-6"
>
	<InView variant="fly-up">
		<section
			class="relative overflow-hidden rounded-2xl border border-border/60 bg-card/60 p-8 md:p-12"
		>
			<div class="mx-auto max-w-3xl space-y-4 text-center">
				<div
					class="inline-flex items-center gap-2 rounded-full border border-border/50 bg-muted/40 px-3 py-1 text-xs font-medium text-muted-foreground"
				>
					<Sparkles class="size-3.5 text-primary" />
					{data.session}
				</div>
				<h1 class="text-3xl font-bold tracking-tight md:text-5xl">
					{orgConfig.shortName} Semester Results Portal
				</h1>
				<p class="text-muted-foreground md:text-lg">
					Access official exam results for {orgConfig.name}. Check grades and track academic performance.
				</p>
			</div>

			<div class="mt-8">
				<ResultSearch
					branches={labels.branches}
					batches={labels.batches}
					programmes={labels.programmes}
				/>
			</div>
		</section>
	</InView>

	<section class="space-y-6">
		<div class="flex items-center justify-between">
			<div class="flex items-center gap-2 text-sm text-muted-foreground">
				<TrendingUp class="size-4 text-primary" />
				<span class="font-medium">
					{resultsData.totalCount.toLocaleString()} results found
				</span>
			</div>
			{#if resultsData.totalPages > 1}
				<span class="text-xs text-muted-foreground">
					Page {currentPage} of {resultsData.totalPages}
				</span>
			{/if}
		</div>

		{#if resultsData.results.length === 0}
			<EmptyArea
				title="No Results Found"
				description="Try adjusting your search filters or clear them to see all results."
			/>
		{:else}
			<StaggerContainer
				class="@md:grid-cols-2 @xl:grid-cols-3 @5xl:grid-cols-4 grid grid-cols-1 gap-4"
			>
				{#each resultsData.results as result (result._id)}
					<ResultCard {result} />
				{/each}
			</StaggerContainer>

			<div class="pt-4">
				<ResultPagination totalPages={resultsData.totalPages} {currentPage} />
			</div>
		{/if}
	</section>
</main>

// apps/platform/app/(common)/(academics)/results/page.tsx
import { ResultCard, SkeletonCard } from "@/components/application/result-card";
import Pagination from "@/components/application/result-pagination";
import SearchBox from "@/components/application/result-search";
import { Skeleton } from "@/components/ui/skeleton";
import { Suspense } from "react";
import { BiSpreadsheet } from "react-icons/bi";
import { getResults } from "~/actions/common.result";

import { BaseHeroSection } from "@/components/application/base-hero";
import AdUnit from "@/components/common/adsense";
import EmptyArea from "@/components/common/empty-area";
import { NoteSeparator } from "@/components/common/note-separator";
import ConditionalRender from "@/components/utils/conditional-render";
import { ErrorBoundaryWithSuspense } from "@/components/utils/error-boundary";
import type { Metadata } from "next";
import { appConfig, orgConfig } from "~/project.config";


async function ResultDisplay({ searchParams }: {
  searchParams?: {
    query?: string;
    page?: string;
    batch?: string;
    branch?: string;
    programme?: string;
    cache?: string;

  }
}) {
  const query = searchParams?.query?.trim() || "";
  const currentPage = Number(searchParams?.page) || 1;
  const filter = {
    batch: Number(searchParams?.batch),
    branch: searchParams?.branch || "",
    programme: searchParams?.programme || "",
  };
  const new_cache = searchParams?.cache === "new";

  const resData = await getResults(query, currentPage, filter, new_cache);
  const { results, totalPages } = resData;

  return <>
    <NoteSeparator label={`${results.length} Results found`} />

    <ConditionalRender condition={results.length > 0}>
      <div className="mx-auto max-w-7xl w-full xl:px-6 grid gap-3 grid-cols-1 @md:grid-cols-2 @xl:grid-cols-3 @5xl:grid-cols-4">
        {results.map((result, i) => {
          return (
            <ResultCard
              key={result._id.toString()}
              result={result}
              style={{
                animationDelay: `${i * 100}ms`,
              }}
            />

          );
        })}
      </div>
      <div className="max-w-7xl mx-auto p-4 empty:hidden">
        <Suspense
          key={"Pagination_key"}
          fallback={<Skeleton className="h-12 w-full " />}
        >
          <Pagination totalPages={totalPages} />
        </Suspense>
      </div>
    </ConditionalRender>
    <ConditionalRender condition={results.length === 0}>
      <EmptyArea
        icons={[BiSpreadsheet]}
        title="No Results Found"
        description="Try adjusting your search filters."
      />
    </ConditionalRender>
  </>
}

export default async function ResultPage(props: {
  searchParams?: Promise<{
    query?: string;
    page?: string;
    batch?: string;
    branch?: string;
    programme?: string;
    cache?: string;
  }>;
}) {
  const searchParams = await props.searchParams;


  return (
    <div className="px-4 md:px-12 xl:px-6 @container">
      <BaseHeroSection
        title={`${orgConfig.shortName} Semester Results Portal`}
        description="Access official exam results for National Institute of Technology Hamirpur. Check grades,
and track academic performance"
      >
        <Suspense
          key={"key_search_bar"}
          fallback={<Skeleton className="h-12 w-full " />}
        >
          <SearchBox new_cache={searchParams?.cache === "new"} />
        </Suspense>
        <script type="application/ld+json" id="search-results-json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SearchResultsPage",
            name: "NITH Results Portal",
            description: "Official examination results portal for NIT Hamirpur",
            url: `${appConfig.url}/results`,
            publisher: orgConfig.jsonLds.EducationalOrganization,
          })}
        </script>
      </BaseHeroSection>

      <ErrorBoundaryWithSuspense
        fallback={
          <EmptyArea
            icons={[BiSpreadsheet]}
            title="Failed to load results"
            description="An error occurred while fetching the results. Please try again later."
          />
        }
        loadingFallback={
          <div className="mx-auto max-w-7xl w-full grid gap-4 grid-cols-1 @md:grid-cols-2 @xl:grid-cols-3 @5xl:grid-cols-4">
            {[...Array(6)].map((_, i) => {
              return <SkeletonCard key={i.toString()} />;
            })}
          </div>
        }
      >
        <ResultDisplay searchParams={searchParams} />

      </ErrorBoundaryWithSuspense>

      <AdUnit
        adSlot="multiplex"
        key={"results-page-ad"}
      />
    </div>
  );
}


export const metadata: Metadata = {
  title:
    orgConfig.shortName + " Results Portal - Check Semester Results Online",
  description:
    orgConfig.shortName +
    " result portal. Search semester results by roll number, name, or course. Access academic records, grades, and transcripts for all programs.",
  applicationName: orgConfig.shortName + " Result Portal",
  alternates: {
    canonical: "/results",
  },
  keywords: [
    orgConfig.shortName,
    orgConfig.name,
    // Primary Keywords
    "NITH Results",
    "NITH Result Portal",
    "NITH Semester Results",
    "NITH Exam Results",

    // Program-Specific
    "NITH BTech Results",
    "NITH MTech Results",
    "NITH BArch Results",
    "NITH MCA Results",
    "NITH PhD Results",

    // Search Functionality
    "Check NITH Results",
    "NITH Result by Roll Number",
    "NITH Result by Name",
    "NITH Result Search",

    // Location-Based
    "NITH Hamirpur Results",
    "NIT Hamirpur Results",

    // Academic Terms
    "NITH Grade Card",
    "NITH Academic Records",
    "NITH Transcript",

    // Technical Terms
    "NITH Result 2024",
    "NITH Odd Semester Results",
    "NITH Even Semester Results",
  ],
  openGraph: {
    title: `NITH Results Portal | ${orgConfig.shortName}`,
    description:
      "Access exam results, grade cards and academic records for all programs at NIT Hamirpur",
    url: `${appConfig.url}/results`,
    images: [
      {
        url: new URL("/og-results.jpg", appConfig.url).toString(),
        width: 1200,
        height: 630,
        alt: "NITH Results Portal Interface",
      },
    ],

    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: `Check NITH Results Online | ${orgConfig.shortName}`,
    description:
      "Instant access to semester exam results for NIT Hamirpur students",
    images: [new URL("/logo.png", appConfig.url).toString()],
  },
  // robots: {
  //     index: true,
  //     follow: true,
  //     nocache: true,
  //     googleBot: {
  //       index: true,
  //       follow: true,
  //     }
  //   },
};
